#import "lecture-template.typ": *

#set document(
  title: "MATH 108A Notes Feb. 3, 2026",
  date: datetime(day: 3, month: 2, year: 2026),
)

#show: template

#example[
  Let $E^(i j)$ denote the $m times n$ matrix whose only nonzero entry is $1$ at the $i$th row and $j$th column. Then $beta = { E^(i j) : 1 <= i <= m, 1 <= j <= n }$ is a basis for $M_(m times n)(FF)$.

  Consider $M_(2 times 2)(FF)$. Then

  $
    beta = { mat(1, 0; 0, 0), mat(0, 1; 0, 0), mat(0, 0; 1, 0), mat(0, 0; 0, 1)}.
  $
]

#exercise(number: none)[
  Let $S$ be the set defined as

  $
    S := { mat(a, a; a, b) : a, b in RR }.
  $

  + Prove that $S$ is a subspace of $M_(2 times 2)(FF)$.

  + Give a basis for $S$.
]

#exercise(number: none)[
  Consider $S = { (x, y, z) in RR^3 : x + y + z = 0 }$.

  + Show that $S$ is a subspace of $RR^3$.

  + Find a basis for $S$.
]

#theorem(number: none)[
  Let $V(FF)$ be a vector space and $beta = { v_i }_(i = 1)^n$ be a subset of of $V$. Then $beta$ is a basis for $V$ if and only if each vector $v in V$ can be expressed uniquely as a linear combination of vectors in $beta$.
]

#proof[
  Let $beta$ be a basis for $V$, and take $v in V$. Then $v$ can be expressed as a linear combination of vectors in $beta$.

  Suppose $v$ can be expressed as two linear combinations of vectors in $beta$. That is,

  $
    v & = & c_1 v_1 + c_2 v_2 + dots.c + c_n v_n & \
    v & = & d_1 v_1 + d_2 v_2 + dots.c + d_n v_n & wide c_i, d_i in FF, v_i in beta thick forall i in [n].
  $

  It follows that

  $
    c_1 v_1 + c_2 v_2 + dots.c + c_n v_n = d_1 v_1 + d_2 v_2 + dots.c + d_n v_n.
  $

  Subtracting the right-hand side from both sides, then using properties of commutativity, associativity, and distribution, we get

  $
    (c_1 - d_1) v_1 + (c_2 - d_2) v_2 + dots.c + (c_n - d_n) v_n = bold(0).
  $

  Since $beta$ is linearly independent, every coefficient $c_i - d_i$ must equal zero. Thus, $c_i = d_i$ for every $i in [n]$, so the two linear combinations of $v$ are actually the same.

  Therefore, every $v in V$ has a unique presentation as a linear combination of vectors in $beta$.

  #div

  Conversely, assume any vector $v in V$ can be expressed uniquely as a linear combination of vectors in $beta$. Then $v$ is in in the the span of $beta$, i.e. $v in span(beta)$. Hence, $span(beta) = V$.

  Now consider the linear combination

  $
    c_1 v_1 + c_2 v_2 + dots.c + c_n v_n = bold(0).
  $

  Take $v = bold(0) in V$. By assumption, the above presentation is unique. The trivial solution is when $c_i = 0$ for every $i in [n]$. It follows that this is the _only_ solution. Hence, by definition, $beta$ is linearly independent.

  These facts combined prove that $beta$ is a basis for $V$.
]

#theorem(number: none)[
  If a vector space $V(FF)$ is generated by a finite set $S$, then some subset of $S$ is a basis for $V$. Hence, $V$ has a finite basis.
]

#proof[
  To begin, suppose either $S$ is empty or $S = { bold(0) }$. Then $V = span(emptyset) = { bold(0) }$, and the empty set $emptyset$ is a subset of $S$ that forms a basis for $V$.

  Otherwise, if $S$ is nonempty and $S != { bold(0) }$, then $S$ contains a nonzero element $v_1$. Then ${ v_1 }$ is a linearly independent subset of $V$.

  If possible, we continue choosing vectors $v_2, v_3, ..., v_k$ from $S$ such that the set $S_k = { v_1, v_2, ..., v_k }$ stays linearly independent. Since $S$ is finite, this process will stop at some $n$.

  We have constructed a linearly independent subset of $S$. That is,

  $
    beta := { v_1, v_2, ..., v_n } subset.eq S.
  $

  Two cases arise: (i) $beta = S$, and (ii) $beta subset S$.

  In the first case, by assumption, $span(beta) = span(S) = V$. Since $beta$ is linearly independent, it is also a basis of $V$.

  We focus on the second case. Our claim is that $beta$ is the desired subset of $S$ which forms a basis for $V$. We show that $span(beta) = V$.

  We know that $beta subset S subset.eq V$ and that $span(S) = V$. A previous result#super([*TODO*]) implies $span(B) subset.eq span(S) = V$. Thus, it suffices to show that $V subset.eq span(B)$. We will show that $S subset.eq span(S)$.

  Let $v in S$. If $v in beta$, then $v in span(beta)$ and we are done. Otherwise, if $v in.not beta$, then the set $beta union { v }$ is linearly dependent because of how we constructed $beta$. We proved last time that this implies $v in span(S)$.

  Hence, $S subset.eq span(beta)$, so $span(S) subset.eq span(beta)$. This implies $V subset.eq span(beta)$, and all together, $V = span(beta)$. Therefore, $beta$ is a basis for $V$.
]

#note[
  The Replacement Theorem says we can extend any linearly independent subset to a basis. The above theorem now says we can reduce any spanning set to a basis.
]

#corollary(number: none)[
  Let $V(FF)$ be a vector space with a finite basis. Then all bases of $V$ are finite, and those bases all have the same number of vectors.
]

#proof[
  Let $beta$ be a basis for $V$ for which $abs(beta) = n < oo$. Then, let $gamma$ be another basis for $V$. Since $gamma$ is a linearly independent subset of $V$, the number of vectors in $gamma$ must not exceed $abs(S)$ where $span(S) = V$.

  Given that $beta$ generates $V$ by definition, we then have $abs(gamma) <= abs(beta)$. Now, reverse the roles of $beta$ and $gamma$ to see that $abs(beta) <= abs(gamma)$. Thus, $abs(beta) = abs(gamma)$. Therefore, all bases of $V$ have the same cardinality.
]

#definition(number: none)[Finite Dimensionality][
  A vector space $V(FF)$ is *finite-dimensional* if it has a basis consisting of a finite number of vectors.
]

#definition(number: none)[Dimension of a Vector Space][
  Let $beta$ be a finite basis of a vector space $V(FF)$ where $abs(beta) = n$, a unique value. Then we call this number $n$ the *dimension* of $V$. We write this as

  $
    dim(V) = n < oo.
  $
]

#example[
  The standard basis for $FF^n$ is $beta = { e_1, e_2, ..., e_n }$. Since $abs(beta) = n$, the dimension of $FF^n$ is $dim(FF^n) = n$.
]

#example[
  $
    dim(M_(m times n)(FF)) = m dot n.
  $
]

#exercise(number: none)[
  Show that $beta = { 1 }$ is a basis for the vector space $CC(CC)$, then deduce that the dimension of this space is $1$.
]

#example[
  The set $beta = { 1, i }$ is a basis for $CC(RR)$. Therefore, $dim(CC(RR)) = 2$.
]

#corollary(number: none)[
  Let $V(FF)$ be a vector space where $dim(V) = n$.

  + Any finite generating set for $V$ contains at least $n$ vectors, and any such set containing exactly $n$ vectors is a basis for $V$.

  + Any linearly independent subset of $V$ consisting of exactly $n$ vectors is a basis for $V$.

  + Every linearly independent subset of $V$ can be extended to a basis for $V$.

  _The proof is left for the next lecture, but you may try it as an exercise!_
]

= Infinite-Dimensional Vector Spaces

We briefly discuss polynomials over a single variable, some subsets of which form infinite-dimensional vector spaces.

Let $P(FF)$ be the set of polynomials in the variable $x$ with coefficients in $FF$. That is,

$
  P(FF) := { a_0 + a_1 x + a_2 x^2 + dots.c + a_n x^n : a_i in FF thick forall i in [n] }.
$

The degree of a nonzero polynomial $f(x) = a_0 + a_1 x + dots.c + a_n x^n$, denoted by $deg(f)$, is the largest nonnegative integer $n$ for which $a_n != 0$. For example,

$
  f(x) = 2x + x^4 => deg(f) = 4.
$

It is convenient to define $deg(bold(0))$ to be $-oo$. Note that the degree of any constant polynomial is zero.

Now, define $P_m (FF)$ to be polynomials in $x$ with degrees at most $m$.

$
  P_m (FF) := { f in P(FF) : deg(f) <= m }.
$

#exercise(number: none)[
  Prove that $beta_m := { 1, x, x^2, ..., x^m }$ is a basis for $P_m (FF)$.
]

The above exercise shows that $P_m (FF)$ is finite-dimensional. The broader set $P(FF)$, however, is *infinite-dimensional*. In fact, $P(FF)$ is generated by the infinite basis

$
  P(FF) = gen(1\, x\, x^2\, ...,).
$
